name: Go
on:
  push: # Run tests on main after PR commit 
    branches:
      # - 'main'
      # - 'release/*'
      - '*'
  pull_request: # Run on all PRs
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Set up Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18
      - name: Test
        run: go test -race -v ./...

  create-release:
    #if: ${{ startsWith(github.ref, 'refs/tags/v') && startsWith('refs/heads/release', github.event.base_ref) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3.3.0
        with:
          go-version: 1.18

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

