name: Go


on:
  push: # Run tests on main after PR commit 
    branches:
		- 'main'
  pull_request: # Run on all PRs
    branches:

jobs:

    test:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.18

        - name: Test
          run: go test -race -v ./...

